"""Minimal backend/main.py - compact, conflict-free.

Keeps only essential endpoints: /linkup_search and /run_scout (SSE).
"""

import asyncio
import sys
import os
from typing import Dict, List

import requests
from fastapi import FastAPI
from pydantic import BaseModel
from fastapi.responses import StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv
<<<<<<< HEAD

# optional sendgrid imports
=======
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

# Load .env variables
load_dotenv()

# Azure OpenAI minimal config
AZURE_KEY = os.getenv("AZURE_OPENAI_KEY")
AZURE_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_DEPLOYMENT = os.getenv("AZURE_OPENAI_GPT_DEPLOYMENT_NAME")

# SendGrid
SENDGRID_KEY = os.getenv("SENDGRID_API_KEY")
REPORT_FROM_EMAIL = os.getenv("REPORT_FROM_EMAIL")

# Linkup API
LINKUP_API_KEY = os.getenv("LINKUP_API_KEY")

>>>>>>> feature/email-report-format
try:
    from sendgrid import SendGridAPIClient
    from sendgrid.helpers.mail import Mail
except Exception:
    SendGridAPIClient = None
    Mail = None

# allow importing my_agents
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from my_agents.discovery_agent import find_companies
from my_agents.deep_dive_agent import run_concurrent_deep_dive

load_dotenv()
SENDGRID_KEY = os.getenv('SENDGRID_API_KEY')
REPORT_FROM_EMAIL = os.getenv('REPORT_FROM_EMAIL')
LINKUP_API_KEY = os.getenv('LINKUP_API_KEY')

app = FastAPI()
app.add_middleware(CORSMiddleware, allow_origins=['*'], allow_methods=['*'], allow_headers=['*'])


<<<<<<< HEAD
class LinkupSearchRequest(BaseModel):
    search_criteria: str
    location: str | None = None
    funding_stage: str | None = None

=======
# -------------------------
# Utility functions for email report
# -------------------------
def build_email_content(criteria: str, attributes: list, results: list[dict]) -> str:
    html = f"<h2>Investment Scout Report</h2>"
    html += f"<p><strong>Search Criteria:</strong> {criteria}</p>"
    html += "<table border='1' cellpadding='5' cellspacing='0'>"
    html += "<tr>" + "".join([f"<th>{attr}</th>" for attr in attributes]) + "</tr>"
    
    for startup in results:
        html += "<tr>" + "".join([f"<td>{startup.get(attr, '-')}</td>" for attr in attributes]) + "</tr>"
    
    html += "</table>"
    html += "<p>Generated by Investment Sourcing Agent</p>"
    return html

def send_email_report(to_email: str, subject: str, html_content: str):
    message = Mail(
        from_email=REPORT_FROM_EMAIL,
        to_emails=to_email,
        subject=subject,
        html_content=html_content
    )
    try:
        sg = SendGridAPIClient(SENDGRID_KEY)
        response = sg.send(message)
        return response.status_code, response.body
    except Exception as e:
        return None, str(e)

# -------------------------
# Linkup API models & endpoint
# -------------------------
class LinkupSearchRequest(BaseModel):
    search_criteria: str
    location: str = None
    funding_stage: str = None

@app.post("/linkup_search")
def linkup_search(payload: LinkupSearchRequest):
    url = "https://api.linkup.com/v1/search"
    headers = {
        "Authorization": f"Bearer {LINKUP_API_KEY}",
        "Content-Type": "application/json"
    }

    data = {"query": payload.search_criteria}
    if payload.location:
        data["location"] = payload.location
    if payload.funding_stage:
        data["funding_stage"] = payload.funding_stage
>>>>>>> feature/email-report-format

@app.post('/linkup_search')
async def linkup_search(payload: LinkupSearchRequest) -> Dict:
    if not LINKUP_API_KEY:
        return {'success': False, 'error': 'LINKUP_API_KEY not configured', 'results': []}
    try:
        url = 'https://api.linkup.so/v2/job_search'
        query = payload.search_criteria
        if payload.location:
            query += f' location:{payload.location}'
        if payload.funding_stage:
            query += f' funding_stage:{payload.funding_stage}'
        resp = requests.post(url, json={'query': query, 'limit': 20}, headers={'Authorization': f'Bearer {LINKUP_API_KEY}'}, timeout=30)
        if resp.status_code == 200:
<<<<<<< HEAD
            data = resp.json()
            jobs = data.get('jobs', data.get('results', []))
            return {'success': True, 'results': jobs if isinstance(jobs, list) else []}
        return {'success': False, 'error': f'Linkup status {resp.status_code}', 'results': []}
    except Exception as e:
        return {'success': False, 'error': str(e), 'results': []}

=======
            return {"success": True, "results": resp.json()}
        else:
            return {"success": False, "status_code": resp.status_code, "error": resp.text}
    except Exception as e:
        return {"success": False, "error": str(e)}

# -------------------------
# Request models
# -------------------------
class EnhanceRequest(BaseModel):
    user_query: str
>>>>>>> feature/email-report-format

class ScoutRequest(BaseModel):
    search_criteria: str
    attributes: List[str]
    email: str

<<<<<<< HEAD

def _safe_send_email(to_email: str, subject: str, html: str):
    if not SENDGRID_KEY or SendGridAPIClient is None:
        return None, 'SendGrid not configured'
    try:
        msg = Mail(from_email=REPORT_FROM_EMAIL, to_emails=to_email, subject=subject, html_content=html)
        sg = SendGridAPIClient(SENDGRID_KEY)
        resp = sg.send(msg)
        return resp.status_code, getattr(resp, 'body', '')
    except Exception as e:
        return None, str(e)


async def run_agent_and_stream(criteria: str, attributes: List[str], email: str):
    yield 'event: status\ndata: starting\n\n'
    await asyncio.sleep(0.1)
    try:
        results = find_companies(criteria=criteria)
    except Exception:
        results = []
    yield f'event: status\ndata: found {len(results)} companies\n\n'
    if results:
=======
# -------------------------
# Enhance with AI endpoint
# -------------------------
@app.post("/enhance_query")
async def enhance_query(payload: EnhanceRequest) -> Dict[str, str]:
    text = payload.user_query or ""
    if openai and AZURE_KEY and AZURE_ENDPOINT and AZURE_DEPLOYMENT:
>>>>>>> feature/email-report-format
        try:
            results = await run_concurrent_deep_dive(results, criteria, attributes)
        except Exception:
            pass
    """backend/main.py — clean implementation (conflict resolved).

    This file mirrors the clean `main2.py` content and resolves previous merge conflicts.
    """

    import asyncio
    import sys
    import os
    from typing import Dict, List

    import requests
    from fastapi import FastAPI
    from pydantic import BaseModel
    from fastapi.responses import StreamingResponse
    from fastapi.middleware.cors import CORSMiddleware
    from dotenv import load_dotenv

    # optional SendGrid
    try:
        from sendgrid import SendGridAPIClient
        from sendgrid.helpers.mail import Mail
    except Exception:
        SendGridAPIClient = None
        Mail = None

    # make my_agents importable
    sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
    from my_agents.discovery_agent import find_companies
    from my_agents.deep_dive_agent import run_concurrent_deep_dive

    load_dotenv()
    SENDGRID_KEY = os.getenv('SENDGRID_API_KEY')
    REPORT_FROM_EMAIL = os.getenv('REPORT_FROM_EMAIL')
    LINKUP_API_KEY = os.getenv('LINKUP_API_KEY')

    app = FastAPI(title="Investment Sourcing Agent")
    app.add_middleware(CORSMiddleware, allow_origins=['*'], allow_methods=['*'], allow_headers=['*'])


    class LinkupSearchRequest(BaseModel):
        search_criteria: str
        location: str | None = None
        funding_stage: str | None = None


    @app.post('/linkup_search')
    async def linkup_search(payload: LinkupSearchRequest) -> Dict:
        if not LINKUP_API_KEY:
            return {'success': False, 'error': 'LINKUP_API_KEY not configured', 'results': []}
        try:
            url = 'https://api.linkup.so/v2/job_search'
            headers = {'Authorization': f'Bearer {LINKUP_API_KEY}', 'Content-Type': 'application/json'}
            query = payload.search_criteria
            if payload.location:
                query += f' location:{payload.location}'
            if payload.funding_stage:
                query += f' funding_stage:{payload.funding_stage}'
            resp = requests.post(url, json={'query': query, 'limit': 20}, headers=headers, timeout=30)
            if resp.status_code == 200:
                data = resp.json()
                jobs = data.get('jobs', data.get('results', []))
                return {'success': True, 'results': jobs if isinstance(jobs, list) else []}
            return {'success': False, 'error': f'Linkup status {resp.status_code}', 'results': []}
        except Exception as e:
            return {'success': False, 'error': str(e), 'results': []}


    class ScoutRequest(BaseModel):
        search_criteria: str
        attributes: List[str]
        email: str


    def _safe_send_email(to_email: str, subject: str, html: str):
        if not SENDGRID_KEY or SendGridAPIClient is None:
            return None, 'SendGrid not configured'
        try:
            msg = Mail(from_email=REPORT_FROM_EMAIL, to_emails=to_email, subject=subject, html_content=html)
            sg = SendGridAPIClient(SENDGRID_KEY)
            resp = sg.send(msg)
            return resp.status_code, getattr(resp, 'body', '')
        except Exception as e:
            return None, str(e)


    async def run_agent_and_stream(criteria: str, attributes: List[str], email: str):
        yield 'event: status\ndata: starting\n\n'
        await asyncio.sleep(0.1)
        try:
            results = find_companies(criteria=criteria)
        except Exception:
            results = []
        yield f'event: status\ndata: found {len(results)} companies\n\n'

        if results:
            try:
                results = await run_concurrent_deep_dive(results, criteria, attributes)
            except Exception:
                pass

        # minimal email body
        html = f'<h3>Report — {len(results)} companies</h3>'
        status, body = _safe_send_email(email, 'Scout Report', html)
        if status:
            yield f'event: status\ndata: email sent ({status})\n\n'
        else:
            yield f'event: status\ndata: email failed: {body}\n\n'

        yield 'event: complete\ndata: {"success": true}\n\n'


    @app.post('/run_scout')
    async def run_scout(payload: ScoutRequest):
        return StreamingResponse(run_agent_and_stream(payload.search_criteria, payload.attributes, payload.email), media_type='text/event-stream')
